# Generated by Django 3.2.16 on 2022-10-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='美多商城编号')),
                ('trade_no', models.CharField(max_length=64, unique=True, verbose_name='支付宝流水号')),
            ],
            options={
                'db_table': 'tb_payment',
            },
        ),
    ]
